### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by r-moeritz** [tonysavon/Chopper-Command-C64#1]
Which assembler must be used to build the sources?

**Comment by tonysavon** [comment]
Hi
Please use Kickassembler
http://theweb.dk/KickAssembler/Main.html#frontpage
Just assemble game.asm and that should give you game.prg, which you can run
straight away.
It can also be crunched with exomizer after that, which is what the
included ChopperCommand.prg file is

**Comment by r-moeritz** [comment]
Thank you!
